/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://6y4udrvd6fa6hhdyxgzucrozzu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-h63zcerxabgb3fa3emuv4b2gaa",
    "aws_cognito_identity_pool_id": "us-west-2:86df762f-be14-4f78-97de-b8fa46b3a91b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_V2tFQ9l0R",
    "aws_user_pools_web_client_id": "1vs048s6aighrbvoq8n13qiev7",
    "oauth": {}
};


export default awsmobile;
